basePath: /api/v1
definitions:
  types.User:
    properties:
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
    type: object
host: localhost:5001
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Hotel Reservation API
  version: "1.0"
paths:
  /user/{id}:
    get:
      consumes:
      - application/json
      description: get accounts
      parameters:
      - description: name search by id
        format: id
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.User'
            type: array
      summary: List accounts
      tags:
      - accounts
swagger: "2.0"
